<?php /** @var kije\Guestbook\Views\BaseView $this  */ ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <!--[if IE]>
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->

        <title><?php echo $this->getData('title'); ?></title>

        <?php $this->renderChildren('head'); ?>
    </head>
    <body id="top">
        <?php $this->renderChildren(); ?>
    </body>
</html>