<?php /** @var kije\Guestbook\Views\PostItem $this */ ?>
<li class="post-item post-id-<?php echo $this->post->id; ?>" id="post-id-<?php echo $this->post->id; ?>">
    <article class="post">
        <header class="post-header">
            <h1><?php echo $this->post->title; ?></h1>
            <time datetime="<?php echo $this->post->date; ?>" class="post-datetime">
                <?php
                $timestamp = strtotime($this->post->date);
                printf('%s at %s', date('l, d. F Y', $timestamp), date('H:i', $timestamp));
                ?>
            </time>
            <span class="user">
                Posted by <?php echo $this->post->user->username; ?>
            </span>
        </header>

        <div class="post-content">
            <?php echo $this->post->content; ?>
        </div>
    </article>
    <?php if (!empty($this->replies)): ?>
        <section class="post-replies">
            <ol class="replies-list">
                <?php $this->renderChildren('replies'); ?>
            </ol>
        </section>
    <?php endif; ?>
    <?php $this->renderChildren('afterPost'); ?>
</li>